package com.java.test.exception;

import java.util.Set;

public class throwsDemo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		 int[]arr=new int[5];
	   try {
			 setZero(arr,10);
		
	} catch (ArrayIndexOutOfBoundsException e) {
               
		// TODO: handle exception
		System.out.println("shuzuchaochubangdingfanwei");
		System.out.println("yichang"+e);
	System.out.println("main()fangfajieshu!");}
	}
	private static void setZero(int[] arr,int index)
		throws ArrayIndexOutOfBoundsException
		{
		       
		
		
		
		
		
	}

}
